/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortlistBRouteImport } from './routes/shortlist-b'
import { Route as ShortlistARouteImport } from './routes/shortlist-a'
import { Route as MidRouteImport } from './routes/mid'
import { Route as EarlyRouteImport } from './routes/early'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as IndexRouteImport } from './routes/index'

const ShortlistBRoute = ShortlistBRouteImport.update({
  id: '/shortlist-b',
  path: '/shortlist-b',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistARoute = ShortlistARouteImport.update({
  id: '/shortlist-a',
  path: '/shortlist-a',
  getParentRoute: () => rootRouteImport,
} as any)
const MidRoute = MidRouteImport.update({
  id: '/mid',
  path: '/mid',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyRoute = EarlyRouteImport.update({
  id: '/early',
  path: '/early',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decision': typeof DecisionRoute
  '/early': typeof EarlyRoute
  '/mid': typeof MidRoute
  '/shortlist-a': typeof ShortlistARoute
  '/shortlist-b': typeof ShortlistBRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decision': typeof DecisionRoute
  '/early': typeof EarlyRoute
  '/mid': typeof MidRoute
  '/shortlist-a': typeof ShortlistARoute
  '/shortlist-b': typeof ShortlistBRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decision': typeof DecisionRoute
  '/early': typeof EarlyRoute
  '/mid': typeof MidRoute
  '/shortlist-a': typeof ShortlistARoute
  '/shortlist-b': typeof ShortlistBRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decision'
    | '/early'
    | '/mid'
    | '/shortlist-a'
    | '/shortlist-b'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decision' | '/early' | '/mid' | '/shortlist-a' | '/shortlist-b'
  id:
    | '__root__'
    | '/'
    | '/decision'
    | '/early'
    | '/mid'
    | '/shortlist-a'
    | '/shortlist-b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionRoute: typeof DecisionRoute
  EarlyRoute: typeof EarlyRoute
  MidRoute: typeof MidRoute
  ShortlistARoute: typeof ShortlistARoute
  ShortlistBRoute: typeof ShortlistBRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shortlist-b': {
      id: '/shortlist-b'
      path: '/shortlist-b'
      fullPath: '/shortlist-b'
      preLoaderRoute: typeof ShortlistBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist-a': {
      id: '/shortlist-a'
      path: '/shortlist-a'
      fullPath: '/shortlist-a'
      preLoaderRoute: typeof ShortlistARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mid': {
      id: '/mid'
      path: '/mid'
      fullPath: '/mid'
      preLoaderRoute: typeof MidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early': {
      id: '/early'
      path: '/early'
      fullPath: '/early'
      preLoaderRoute: typeof EarlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionRoute: DecisionRoute,
  EarlyRoute: EarlyRoute,
  MidRoute: MidRoute,
  ShortlistARoute: ShortlistARoute,
  ShortlistBRoute: ShortlistBRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
